spring.application.name=LiveQuiz-QuizService

spring.mongodb.database=livequiz_quizservice_db
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/livequiz_quizservice_db}

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-null-for-primitives=true

logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.com.quizservice.livequiz=INFO

spring.threads.virtual.enabled=true
