spring.application.name=LiveQuiz-QuizService

spring.mongodb.database=livequiz_quizservice_db
spring.mongodb.uri=mongodb://localhost:27017/${spring.mongodb.database}

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-null-for-primitives=true
